services:
  reservas:
    build: .
    container_name: reservas_service
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - reservas_db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: reservas_rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'

  reservas_db:
    image: postgres:16
    container_name: reservas_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=reservas_user
      - POSTGRES_PASSWORD=reservas_pass
      - POSTGRES_DB=reservasdb
    volumes:
      - reservas_db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  reservas_db_data:
